import json

new_cells = []

# Cell 0: Imports
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["import torch\n", "import torch.nn as nn\n", "import torch.optim as optim\n", "from torch.utils.data import Dataset, DataLoader\n", "from sklearn.preprocessing import StandardScaler\n", "from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score\n", "from sklearn.model_selection import train_test_split\n", "import numpy as np\n", "import matplotlib.pyplot as plt\n", "import seaborn as sns\n", "import struct\n", "from pathlib import Path\n", "import math\n", "import json\n", "from datetime import datetime\n", "from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence\n", "\n", "torch.backends.cudnn.benchmark = True\n", "torch.backends.cudnn.enabled = True\n", "torch.backends.cudnn.deterministic = False\n", "\n", "DEVICE = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n", "print(f\"Using device: {DEVICE}")\n"]})

# Cell 1: PipeDataset и collate_fn
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["class PipeDataset(Dataset):\n", "    def __init__(self, data_list, labels, scaler=None, fit_scaler=False):\n", "        self.data_list = data_list\n", "        self.labels = labels\n", "        if fit_scaler:\n", "            all_data = np.vstack(data_list)\n", "            self.scaler = StandardScaler().fit(all_data)\n", "        else:\n", "            self.scaler = scaler\n", "        self.data_list = [torch.FloatTensor(self.scaler.transform(sample)) for sample in self.data_list]\n", "        self.labels = torch.LongTensor(labels)\n", "    def __len__(self): return len(self.data_list)\n", "    def __getitem__(self, idx): return self.data_list[idx], self.labels[idx]\n", "\n", "def collate_fn(batch):\n", "    data_list, labels = zip(*batch)\n", "    max_len = max([d.shape[0] for d in data_list])\n", "    padded_data, lengths = [], []\n", "    for data in data_list:\n", "        length = data.shape[0]\n", "        lengths.append(length)\n", "        padding = torch.zeros(max_len - length, data.shape[1])\n", "        padded = torch.cat([data, padding], dim=0)\n", "        padded_data.append(padded)\n", "    data_batch = torch.stack(padded_data)\n", "    labels_batch = torch.stack(labels)\n", "    mask = torch.zeros(data_batch.shape[:2])\n", "    for i, length in enumerate(lengths): mask[i, :length] = 1\n", "    return data_batch, labels_batch, torch.tensor(lengths), mask\n"]})

# Cell 2: Модель CNN-LSTM
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["class PipeCNNLSTM(nn.Module):\n", "    def __init__(self, input_channels=8, n_classes=2, cnn_filters=[32, 64, 128], lstm_hidden=128, lstm_layers=2, dropout=0.3):\n", "        super().__init__()\n", "        cnn_layers = []\n", "        in_channels = input_channels\n", "        for filters in cnn_filters:\n", "            cnn_layers.extend([nn.Conv1d(in_channels, filters, kernel_size=5, padding=2), nn.BatchNorm1d(filters), nn.ReLU(), nn.MaxPool1d(2), nn.Dropout(dropout)])\n", "            in_channels = filters\n", "        self.cnn = nn.Sequential(*cnn_layers)\n", "        self.lstm = nn.LSTM(input_size=cnn_filters[-1], hidden_size=lstm_hidden, num_layers=lstm_layers, batch_first=True, bidirectional=True, dropout=dropout if lstm_layers > 1 else 0)\n", "        self.classifier = nn.Sequential(nn.Linear(lstm_hidden * 2, 64), nn.LeakyReLU(), nn.Dropout(dropout), nn.Linear(64, n_classes))\n", "        self._init_weights()\n", "    def _init_weights(self):\n", "        for p in self.parameters():\n", "            if p.dim() > 1: nn.init.xavier_uniform_(p)\n", "    def forward(self, x, lengths=None):\n", "        x = x.transpose(1, 2)\n", "        x = self.cnn(x)\n", "        x = x.transpose(1, 2)\n", "        if lengths is not None:\n", "            lengths = lengths.clone()\n", "            for _ in range(2): lengths = (lengths + 1) // 2\n", "            lengths = torch.clamp(lengths, max=x.shape[1])\n", "            packed = pack_padded_sequence(x, lengths.cpu(), batch_first=True, enforce_sorted=False)\n", "            _, (h_n, _) = self.lstm(packed)\n", "        else:\n", "            _, (h_n, _) = self.lstm(x)\n", "        h_cat = torch.cat([h_n[-2], h_n[-1]], dim=1) if self.lstm.bidirectional else h_n[-1]\n", "        return self.classifier(h_cat)\n"]})

# Cell 3: Функции чтения raw файлов
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["def read_raw_file(filepath):\n", "    path = Path(filepath)\n", "    if not path.exists(): raise FileNotFoundError(f\"File not found: {path}\")\n", "    with open(path, \"rb\") as f: data = f.read()\n", "    if len(data) < 17: raise ValueError(\"File too short\")\n", "    x = struct.unpack_from(\">i\", data, 0)[0]\n", "    y = struct.unpack_from(\">i\", data, 4)[0]\n", "    thicknom = struct.unpack_from(\">d\", data, 8)[0]\n", "    defective = struct.unpack_from(\">B\", data, 16)[0]\n", "    num_values = x * y\n", "    matrix = struct.unpack(f\">{num_values}d\", data[17:17+num_values*8])\n", "    return {\"matrix\": np.array(matrix, dtype=np.float32).reshape(x, y), \"defective\": defective, \"thicknom\": thicknom}\n", "\n", "def load_dataset_from_folder(folder_path, verbose=True):\n", "    folder = Path(folder_path)\n", "    raw_files = list(folder.glob(\"*.raw\"))\n", "    if not raw_files: raise FileNotFoundError(f\"No .raw files found in {folder_path}\")\n", "    if verbose: print(f\"Found files: {len(raw_files)}\")\n", "    data_list, labels, thicknom_list = [], [], []\n", "    for file_path in raw_files:\n", "        try:\n", "            result = read_raw_file(file_path)\n", "            data_list.append(result[\"matrix\"])\n", "            labels.append(result[\"defective\"])\n", "            thicknom_list.append(result[\"thicknom\"])\n", "        except Exception as e: print(f\"Error reading {file_path.name}: {e}\")\n", "    if verbose: print(f\"Loaded: {len(data_list)} files\")\n", "    return data_list, np.array(labels), thicknom_list\n"]})

# Cell 4: Функции обучения и оценки
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["def train_epoch(model, loader, criterion, optimizer, device, scaler):\n", "    model.train()\n", "    total_loss, correct, total = 0, 0, 0\n", "    for data, labels, lengths, mask in loader:\n", "        data, labels, lengths = data.to(device, non_blocking=True), labels.to(device, non_blocking=True), lengths.to(device, non_blocking=True)\n", "        optimizer.zero_grad()\n", "        with torch.amp.autocast(\"cuda\"):\n", "            outputs = model(data, lengths)\n", "            loss = criterion(outputs, labels)\n", "        scaler.scale(loss).backward()\n", "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)\n", "        scaler.step(optimizer)\n", "        scaler.update()\n", "        total_loss += loss.item() * data.size(0)\n", "        _, predicted = outputs.max(1)\n", "        total += labels.size(0)\n", "        correct += predicted.eq(labels).sum().item()\n", "    return total_loss / total, 100. * correct / total\n", "\n", "def evaluate(model, loader, criterion, device):\n", "    model.eval()\n", "    total_loss, correct, total = 0, 0, 0\n", "    all_preds, all_labels = [], []\n", "    with torch.no_grad():\n", "        for data, labels, lengths, mask in loader:\n", "            data, labels, lengths = data.to(device, non_blocking=True), labels.to(device, non_blocking=True), lengths.to(device, non_blocking=True)\n", "            with torch.cuda.amp.autocast():\n", "                outputs = model(data, lengths)\n", "                loss = criterion(outputs, labels)\n", "            total_loss += loss.item() * data.size(0)\n", "            _, predicted = outputs.max(1)\n", "            total += labels.size(0)\n", "            correct += predicted.eq(labels).sum().item()\n", "            all_preds.extend(predicted.cpu().numpy())\n", "            all_labels.extend(labels.cpu().numpy())\n", "    return total_loss / total, 100. * correct / total, all_preds, all_labels\n"]})

# Cell 5: Scheduler с Warmup
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["def get_cosine_schedule_with_warmup(optimizer, num_warmup_steps, num_training_steps, min_lr=1e-7):\n", "    def lr_lambda(current_step):\n", "        if current_step < num_warmup_steps: return float(current_step) / float(max(1, num_warmup_steps))\n", "        progress = float(current_step - num_warmup_steps) / float(max(1, num_training_steps - num_warmup_steps))\n", "        return max(0.0, 0.5 * (1.0 + math.cos(math.pi * progress)))\n", "    return optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)\n"]})

# Cell 6: Функции создания папки результатов и построения графиков
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["def create_results_folder(epochs, batch_size, learning_rate, model_type=\"CNN_LSTM\", base_dir=\"results\"):\n", "    timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n", "    folder_name = f\"{model_type}_{epochs}epochs_{batch_size}batch_{learning_rate}lr_{timestamp}\"\n", "    results_dir = Path(base_dir) / folder_name\n", "    results_dir.mkdir(parents=True, exist_ok=True)\n", "    print(f\"\\n📁 Папка результатов: {results_dir.absolute()}\")\n", "    return results_dir, folder_name\n", "\n", "def plot_training_history(history, results_dir, folder_prefix, save_name=\"training_plot.png\"):\n", "    epochs = range(1, len(history[\"train_loss\"]) + 1)\n", "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n", "    axes[0].plot(epochs, history[\"train_loss\"], \"b-\", label=\"Train Loss\", linewidth=2)\n", "    axes[0].plot(epochs, history[\"val_loss\"], \"r--\", label=\"Val Loss\", linewidth=2)\n", "    axes[0].set_xlabel(\"Эпоха\", fontsize=11); axes[0].set_ylabel(\"Потеря (Loss)\", fontsize=11)\n", "    axes[0].set_title(\"📉 Динамика потери CNN-LSTM\", fontsize=13, fontweight=\"bold\")\n", "    axes[0].legend(fontsize=10); axes[0].grid(True, alpha=0.3); axes[0].set_axisbelow(True)\n", "    axes[1].plot(epochs, history[\"train_acc\"], \"b-\", label=\"Train Acc\", linewidth=2)\n", "    axes[1].plot(epochs, history[\"val_acc\"], \"r--\", label=\"Val Acc\", linewidth=2)\n", "    axes[1].set_xlabel(\"Эпоха\", fontsize=11); axes[1].set_ylabel(\"Точность (%)\", fontsize=11)\n", "    axes[1].set_title(\"📈 Динамика точности CNN-LSTM\", fontsize=13, fontweight=\"bold\")\n", "    axes[1].legend(fontsize=10); axes[1].grid(True, alpha=0.3); axes[1].set_axisbelow(True)\n", "    plt.tight_layout()\n", "    save_path = results_dir / f\"{folder_prefix}_{save_name}\"\n", "    plt.savefig(save_path, dpi=300, bbox_inches=\"tight\")\n", "    plt.show()\n", "    print(f\"💾 График сохранён: {save_path}\")\n", "    return save_path\n"]})

# Cell 7: Загрузка данных
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["DATA_FOLDER = \"dataset\"\n", "print(\"Loading data...\")\n", "data_list, labels, thicknom_list = load_dataset_from_folder(DATA_FOLDER)\n", "X_train, X_val, y_train, y_val, thicknom_train, thicknom_val = train_test_split(data_list, labels, thicknom_list, test_size=0.2, random_state=42, stratify=labels)\n", "print(f\"Train: {len(X_train)}, Val: {len(X_val)}\")\n", "BATCH_SIZE = 128\n", "train_dataset = PipeDataset(X_train, y_train, scaler=None, fit_scaler=True)\n", "val_dataset = PipeDataset(X_val, y_val, scaler=train_dataset.scaler, fit_scaler=False)\n", "train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn, num_workers=4, pin_memory=True, persistent_workers=True)\n", "val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn, num_workers=4, pin_memory=True, persistent_workers=True)\n", "print(f\"✅ DataLoader создан! Train batches: {len(train_loader)}, Val batches: {len(val_loader)}\")\n"]})

# Cell 8: Конфигурация
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["print(\"🔥 GPU:\", torch.cuda.get_device_name(0) if torch.cuda.is_available() else \"CPU\")\n", "if torch.cuda.is_available(): print(f\"📊 Память GPU: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB\")\n", "EPOCHS, LEARNING_RATE, N_CLASSES, MODEL_TYPE = 250, 0.005, 2, \"CNN_LSTM\"\n", "results_dir, folder_prefix = create_results_folder(epochs=EPOCHS, batch_size=BATCH_SIZE, learning_rate=LEARNING_RATE, model_type=MODEL_TYPE, base_dir=\"results\")\n"]})

# Cell 9: Инициализация модели
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["model = PipeCNNLSTM(input_channels=8, n_classes=N_CLASSES, cnn_filters=[32, 64, 128], lstm_hidden=128, lstm_layers=2, dropout=0.3).to(DEVICE)\n", "criterion = nn.CrossEntropyLoss()\n", "optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)\n", "scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=EPOCHS // 10, num_training_steps=EPOCHS)\n", "scaler = torch.amp.GradScaler(\"cuda\")\n", "print(f\"✅ Модель создана на {DEVICE}, Параметры: {sum(p.numel() for p in model.parameters()):,}\")\n"]})

# Cell 10: Цикл обучения
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["history = {\"train_loss\": [], \"train_acc\": [], \"val_loss\": [], \"val_acc\": []}\n", "best_val_acc, patience_counter, early_stop_patience = 0, 0, 50\n", "print(\"Training CNN-LSTM...\")\n", "for epoch in range(EPOCHS):\n", "    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer, DEVICE, scaler)\n", "    val_loss, val_acc, val_preds, val_labels = evaluate(model, val_loader, criterion, DEVICE)\n", "    scheduler.step()\n", "    history[\"train_loss\"].append(train_loss); history[\"train_acc\"].append(train_acc); history[\"val_loss\"].append(val_loss); history[\"val_acc\"].append(val_acc)\n", "    if val_acc > best_val_acc:\n", "        best_val_acc = val_acc; patience_counter = 0\n", "        torch.save(model.state_dict(), results_dir / \"best_pipe_cnn_lstm.pth\")\n", "        print(f\"  ⭐ Новая лучшая модель! Acc: {val_acc:.2f}%\")\n", "    else: patience_counter += 1\n", "    if (epoch + 1) % 10 == 0 or epoch == 0: print(f\"Epoch {epoch+1:02d} | Train Loss: {train_loss:.4f} Acc: {train_acc:.2f}% | Val Loss: {val_loss:.4f} Acc: {val_acc:.2f}%\")\n", "    if patience_counter >= early_stop_patience:\n", "        print(f\"\\n🛑 Early stopping на эпохе {epoch+1}\"); break\n"]})

# Cell 11: Сохранение результатов
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["plot_training_history(history, results_dir, folder_prefix)\n", "print(\"\\n=== ФИНАЛЬНАЯ ОЦЕНКА ===\")\n", "final_loss, final_acc, y_pred, y_true = evaluate(model, val_loader, criterion, DEVICE)\n", "print(f\"Финальная точность на валидации: {final_acc:.2f}%\")\n", "model.eval(); all_probs, all_labels = [], []\n", "with torch.no_grad():\n", "    for data, labels, lengths, mask in val_loader:\n", "        data, lengths = data.to(DEVICE), lengths.to(DEVICE)\n", "        outputs = model(data, lengths)\n", "        probs = torch.softmax(outputs, dim=1)\n", "        all_probs.extend(probs[:, 1].cpu().numpy()); all_labels.extend(labels.numpy())\n", "try: print(f\"ROC-AUC Score: {roc_auc_score(all_labels, all_probs):.4f}\")\n", "except Exception as e: print(f\"ROC-AUC не вычислен: {e}\")\n", "print(\"\\n📋 Classification Report:\"); print(classification_report(y_true, y_pred, target_names=[\"Годный (0)\", \"Брак (1)\"]))\n", "cm = confusion_matrix(y_true, y_pred); print(\"\\n🗂️ Confusion Matrix:\"); print(cm)\n", "plt.figure(figsize=(6, 5)); sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\", xticklabels=[\"Годный\", \"Брак\"], yticklabels=[\"Годный\", \"Брак\"])\n", "plt.xlabel(\"Предсказано\", fontsize=11); plt.ylabel(\"Фактически\", fontsize=11); plt.title(\"🎯 Матрица ошибок\", fontsize=13, fontweight=\"bold\")\n", "plt.tight_layout(); cm_save_path = results_dir / f\"{folder_prefix}_confusion_matrix.png\"\n", "plt.savefig(cm_save_path, dpi=300, bbox_inches=\"tight\"); plt.show(); print(f\"💾 Матрица ошибок сохранена: {cm_save_path}\")\n"]})

# Cell 12: Сохранение конфигурации
new_cells.append({"cell_type": "code", "metadata": {}, "outputs": [], "execution_count": None, "source": ["config_path = results_dir / f\"{folder_prefix}_config.json\"\n", "config = {\"model_type\": MODEL_TYPE, \"epochs\": EPOCHS, \"batch_size\": BATCH_SIZE, \"learning_rate\": LEARNING_RATE, \"n_classes\": N_CLASSES, \"input_channels\": 8, \"cnn_filters\": [32, 64, 128], \"lstm_hidden\": 128, \"lstm_layers\": 2, \"dropout\": 0.3, \"best_val_acc\": best_val_acc, \"train_samples\": len(X_train), \"val_samples\": len(X_val), \"actual_epochs\": len(history[\"train_acc\"]), \"timestamp\": datetime.now().isoformat(), \"device\": str(DEVICE)}\n", "with open(config_path, \"w\", encoding=\"utf-8\") as f: json.dump(config, f, indent=2, ensure_ascii=False)\n", "print(f\"💾 Конфигурация сохранена: {config_path}\")\n", "print(\"\\n\" + \"=\"*60); print(\"📁 ВСЕ ФАЙЛЫ СОХРАНЕНЫ В ПАПКУ:\"); print(f\"   {results_dir.absolute()}\")\n", "print(\"\\n📄 Список сохранённых файлов:\"); print(f\"   1. {folder_prefix}_best_pipe_cnn_lstm.pth (веса модели)\"); print(f\"   2. {folder_prefix}_training_plot.png (графики)\"); print(f\"   3. {folder_prefix}_confusion_matrix.png (матрица ошибок)\"); print(f\"   4. {folder_prefix}_config.json (параметры)\"); print(\"=\"*60)\n"]})

new_notebook = {"cells": new_cells, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"name": "python", "version": "3.8.0"}}, "nbformat": 4, "nbformat_minor": 5}

with open("/workspace/CNN_LSTM_updated.ipynb", "w", encoding="utf-8") as f:
    json.dump(new_notebook, f, indent=1, ensure_ascii=False)

print("✅ Файл CNN_LSTM_updated.ipynb успешно создан!")
print(f"   Количество ячеек: {len(new_cells)}")
